export { HomePageText } from './HomePage'
export { gfMainMenu } from './MainManu/gfMainMenu'
export { gfSearch } from './Search/search'
export { gfAdmin } from './Admin/admin'
export { gfAdminMain } from './Admin/main'