export { HomePageText } from './HomePage'
export { gfMainMenu } from './MainManu/gfMainMenu'
export { gfSearch } from './Search/search'
export { gfArticleStore } from './Article/articleStore'
export { gfBanners } from './Banners/gfBanners'